### ISSUE TITLE
https支持

### ISSUE THREAD

**Issue by Leeiio** [staticfile/static#11]
不然https的网站就没法用到这个优秀的服务了。

**Comment by JokerQyou** [comment]
UIKit 的文件，在 HTTP 下是有的，正常使用，按照这个 issue 的说法换成 HTTPS 访问就 404 了。
HTTP 地址 http://cdn.staticfile.org/uikit/2.12.0/css/uikit.almost-flat.min.css 
HTTPS 地址 https://dn-staticfile.qbox.me/uikit/2.12.0/css/uikit.almost-flat.min.css

**Comment by Xuanwo** [comment]
确实404

**Comment by laike9m** [comment]
还不支持么。。。

**Comment by Xuanwo** [comment]
Hello，资源404的问题已经修复了，有新的问题欢迎另外开启issue反馈。
关于HTTPS的问题，我已经联系七牛看看能不能购买`staticfile.org`的证书了，有任何反馈我都会及时发布在issues区，目前请使用`https://dn-staticfile.qbox.me/jquery/2.0.3/jquery.js`引用，谢谢大家~

**Comment by likebeta** [comment]
http和https没法自适应， 挺蛋疼的
