### ISSUE TITLE
能否添加dojo,dijit,dojox

### ISSUE THREAD

**Issue by dalingng** [staticfile/static#113]
能否添加dojo,dijit,dojox，现在最新版是1.9.3，这个库实在是好用，谢谢了。
官网地址：
http://www.dojotoolkit.org
git:
https://github.com/dojo/dojo
https://github.com/dojo/dijit
https://github.com/dojo/dojox

**Comment by Xuanwo** [comment]
您可以提交一个PR

**Comment by Xuanwo** [comment]
已经加入了CDNJS
