### ISSUE TITLE
你们的ssl。。。是随便搞的吧？

### ISSUE THREAD

**Issue by tossp** [staticfile/static#161]
您尝试访问的是 cdn.staticfile.org，但实际上访问的却是标识为 kyfw.12306.cn 的服务器。

**Comment by ligboy** [comment]
https://dn-staticfile.qbox.me/ 使用这个替代就好了。这是staticfile的qiniu分配的https域名。

**Comment by yutianhot** [comment]
还是建议搞单独的https出来

**Comment by ligboy** [comment]
@yutianhot 不能的原因是，qiniu只是其基层cdn服务商的其中之一客户，为了兼容xp等老的系统和IE浏览器不具有sni，https还能不支持虚拟主机。

**Comment by ralphhuang** [comment]
使用https://dn-staticfile.qbox.me/替换的方案可行

**Comment by Xuanwo** [comment]
Fixed.
