### ISSUE TITLE
更新ionic 1.0.0-beta.13

### ISSUE THREAD

**Issue by linzhe121** [staticfile/static#193]
cdnjs已更新https://github.com/cdnjs/cdnjs/tree/master/ajax/libs/ionic/1.0.0-beta.13
http://cdn.staticfile.org/ionic/1.0.0-beta.13/js/ionic.js无法访问

**Comment by Xuanwo** [comment]
刚才测试了一下，是可以访问的，你再检查一下呢？

**Comment by Xuanwo** [comment]
CDNJS将会定期同步~
