### ISSUE TITLE
增加ExtJS5.1.0

### ISSUE THREAD

**Issue by MaOrKsSi** [staticfile/static#218]
如题。我看到了4.2.1，所以建议增加5.1.0，我可以提供一个修正後的版本。

**Comment by Xuanwo** [comment]
你可以提交一个PR，我会尽快审核。

**Comment by Xuanwo** [comment]
extjs已经跟随CDNJS更新至6.0.0

**Comment by MaOrKsSi** [comment]
面对满屏幕英文，我根本看不懂，所以回复慢了，不好意思。其实extjs有个版权问题，最好不要公开extjs，以免触犯法律。
