### ISSUE TITLE
七牛自家的 JavaScript SDK 居然在CDN上面没有...

### ISSUE THREAD

**Issue by GameXG** [staticfile/static#221]
https://github.com/qiniupd/qiniu-js-sdk/
http://developer.qiniu.com/docs/v6/sdk/javascript-sdk.html

七牛 JavaScript SDK 依赖的 Plupload 也没有.

**Comment by SunLn** [comment]
#105 Plupload有提PR，没有合并。囧。

**Comment by SunLn** [comment]
#105 合并了。js-sdk 后续会提pr。

**Comment by GameXG** [comment]
表示 Plupload 还是搜索不到。

**Comment by GameXG** [comment]
同时 七牛 js sdk 提交了 Pull Request 。

**Comment by Xuanwo** [comment]
已经合并了
