### ISSUE TITLE
Semantic UI 版本没更新，官网都1.7.3了，这里还是0.19.3

### ISSUE THREAD

**Issue by zuroc** [staticfile/static#222]
我去cdnjs看了，那边是最新版本，这边没有同步？

**Comment by tvvocold** [comment]
@forrest-mao

**Comment by tvvocold** [comment]
@ikbear
求更新，我需要1.5.0版本

**Comment by Xuanwo** [comment]
提交一个PR吧，我尽快合并。
什么时候服务器那边更新- -，就看七牛了。。

**Comment by jingweizheng** [comment]
问一下，css里面默认使用google字体怎么办？加载很慢啊

**Comment by tvvocold** [comment]
@Xuanwo 
能否顺便反代下谷歌字体？
https://hjc.im/google-fonts-reverse-proxy/

**Comment by Xuanwo** [comment]
原理限制，并不能

**Comment by tvvocold** [comment]
@Xuanwo 
我可以去申请台主机，供你们部署 fonts.staticfile.org ，可以吗？

**Comment by jingweizheng** [comment]
我都用自己的七牛修改谷歌字体指向360的反代了。。。。好不爽啊

**Comment by Xuanwo** [comment]
我也很想做这样的事情，但是很遗憾我并不是七牛的工作人员，所以我也没有办法承诺或者答应什么，非常抱歉= =

**Comment by tvvocold** [comment]
hi @Xuanwo ，
我只需要 staticfile.org 加入一个 A 记录即可，这个我需要找谁呢？

**Comment by Xuanwo** [comment]
@jingweizheng 你好，七牛是如何支持谷歌反代的呢？我看看能不能实现。

CDNJS的更新脚本已经修复，Semantic UI已经跟随CDNJS更新~

**Comment by jingweizheng** [comment]
@Xuanwo css修改：
@import url('http://fonts.useso.com/css?family=Lato:400,700,400italic,700italic&subset=latin');
