### ISSUE TITLE
搜索 font-awesome 的问题

### ISSUE THREAD

**Issue by JokerQyou** [staticfile/static#225]
使用 `font` 可以搜索出来，但是排在非常后面；
使用 `font-` 搜索不出来；
使用 `font-a` 和更完整的关键词也搜索不出来。

**Comment by s-kias** [comment]
用 `awesome` 可以搜索出

**Comment by Xuanwo** [comment]
搜索这一块确实需要优化一下，有好的想法么？

**Comment by Xuanwo** [comment]
Fixed.
