### ISSUE TITLE
"TWITTER-BOOTSTRAP"里所有的资源都表示: "document not found"

### ISSUE THREAD

**Issue by tinysnake** [staticfile/static#229]
版本: 3.3.1
地区: 福建电信(福州).

话说bootstrap已经更新到3.3.2了.

**Comment by phoenixgao** [comment]
+1

**Comment by sintrb** [comment]
我查询jquery，最想要的是jquery.js，但是最先给出的是jquery-i18n的，能优化一下查询方面么，谢谢

**Comment by halk947** [comment]
+1
北京联通

**Comment by ssddi456** [comment]
+ 3,3,1是空的  3.3.0ok

**Comment by Xuanwo** [comment]
刚才我确认了一下，3.3.1和3.3.0都是可以正常访问到的。

麻烦确认一下现在还是不能访问到么？

**Comment by tinysnake** [comment]
现在可以了..
