### ISSUE TITLE
查询优化

### ISSUE THREAD

**Issue by sintrb** [staticfile/static#237]
我查询jquery，最想要的是jquery.js，但是最先给出的是jquery-i18n的，能优化一下查询方面么，谢谢

**Comment by ssddi456** [comment]
顶
我发现完全匹配的结果居然都被过滤掉了，比如搜jquery第一个不是jquery，搜bootstrap第一个不是bootstrap

**Comment by sintrb** [comment]
后面我发现其实jquery的话，直接没必要输入关键字，自然排列的第一个就是了，不过也感觉这样子怪怪的。

**Comment by Xuanwo** [comment]
观察源码的话，好像直接利用id进行搜索的。
你们或许可以给staticfile.github.io那边提交一个PR？

**Comment by max-wen** [comment]
顶

还有就是[首页](http://www.staticfile.org)的搜索框, 其实真没必要实时ajax搜索  长一点的单词基本上打不出来， 因为一直在异步搜索  建议优化成回车搜索  

最后支持一下国内的开放CDN事业，顶七牛 :+1:

**Comment by Xuanwo** [comment]
Fixed.

**Comment by TechQuery** [comment]
@Xuanwo ，@sintrb @ssddi456 提的问题并未修复 ——

我逐个字母输入“jquery”，下拉提示框中出现的全是 **jQuery 插件**，按回车之后显示的是 第一个提示项对应的库……
