### ISSUE TITLE
服务是不是不可用了？

### ISSUE THREAD

**Issue by superhj1987** [staticfile/static#240]
我按照说明安装了sfile: npm install -g sfile，然后使用sfile search jquery，显示***没有结果***。搜索其他的也是同样的结果。另外，在 http://staticfile.org/ 的输入框里输入任何开源库的名字都没有任何反应。是我使用有问题吗？还是服务异常了？

**Comment by htynkn** [comment]
+1 我也是没法使用了

**Comment by int64ago** [comment]
http://cdn.int64ago.org/
使用这个替代

**Comment by blindlf** [comment]
API没有了. 404，http://api.staticfile.org/v1/search?count=10&q=jquery

**Comment by sofish** [comment]
域名正在转到七牛，服务器依然可用，目前只是不能搜索
