### ISSUE TITLE
这个项目还在维护吗？

### ISSUE THREAD

**Issue by wong2** [staticfile/static#247]
ref-cdnjs 已经是4个月之前的了。

**Comment by xfight0** [comment]
这个库主要是靠大家维护的，一起来贡献
[参考](http://www.staticfile.org/about.html#howto)

**Comment by GameXG** [comment]
但是没人审核 Pull Request，我二月份的Pull Request还在那里挂着。

https://github.com/staticfile/static/pulls

**Comment by XMap** [comment]
比较关注 . 项目的更新问题~~~

**Comment by wong2** [comment]
比如可以有个脚本自动更新 ref-cdnjs 吗？

**Comment by sinkcup** [comment]
pure css 也很久没更新了…… 支持  @wong2 的提议

**Comment by sinkcup** [comment]
建议 @ikbear @sofish @xushiwei 多增加几个项目管理员，这个项目比较简单，只要会审核pull request就行了。

**Comment by Xuanwo** [comment]
@sinkcup 已经发邮件申请了，不知道怎么说= =

**Comment by Xuanwo** [comment]
手动更新了一发cdnjs

**Comment by int64ago** [comment]
http://cdn.int64ago.org/ 
我觉得世界上有一个 CDNJS 就够了，有需要的就向 CDNJS 提 PR，我这里只是用七牛做了个镜像，并且加了良好的索引功能，欢迎使用！

**Comment by rebirthing** [comment]
@int64ago :+1:

**Comment by laike9m** [comment]
@int64ago 你这个支持 SPDY/HTTP 2 么？

**Comment by int64ago** [comment]
这个得取决于七牛，目前看未支持

**Comment by Xuanwo** [comment]
已经和七牛的人联系上了，维护工作将会在近期重新展开，服务器端的更新也会在本周末完成~

**Comment by PeterDaveHello** [comment]
#336
