### ISSUE TITLE
ref-cdnjs  中的文件的url链接地址怎么算出来的

### ISSUE THREAD

**Issue by blueseller** [staticfile/static#249]
RT，
ref-cdnjs中的url是如何算出来的。

麻烦大神告诉下。谢谢！

**Comment by SyuTingSong** [comment]
同问，没人回答

**Comment by Xuanwo** [comment]
什么叫怎么算出来？

**Comment by SyuTingSong** [comment]
就是看到ref-cdnjs里有需要用的库，怎么拼出相应的staticfile的URL

**Comment by Xuanwo** [comment]
http://cdn.staticfile.org/库名/版本号/资源名

**Comment by SyuTingSong** [comment]
我看到现在引用的cdnjs是 cc90504c 版，在他们的库里找到了jquery 2.1.4，可是按规则拼出来 http://cdn.staticfile.org/jquery/2.1.4/jquery.js 却收到404

**Comment by Xuanwo** [comment]
- -，因为七牛那边没有执行服务器上的脚本。
所以尽管我合并了，但是七牛的CDN并没有更新。

**Comment by Xuanwo** [comment]
@SyuTingSong http://cdn.staticfile.org/jquery/2.1.4/jquery.js 现在已经更新了~
