### ISSUE TITLE
搜索结果太扯淡

### ISSUE THREAD

**Issue by sizhang** [staticfile/static#250]
搜索结果出来的，N多一些不相关的东西，根本搜索不到想要的，不维护就干脆下线，要维护就要做好

**Comment by sofish** [comment]
1. 这是一个公益项目，可能并不是一切都如你所想，我们的目标是帮助开发者，为开发者提供免费 CDN，我们已经尽可能做好。
2. 这是一个开源的项目，如果你希望贡献，可以提交更好的方案。
3. 如果你想体验更好的服务，可能直接使用七牛的 CDN 自己存储也是有免费的额度；当然商用也很便宜（利益相关：我不是七牛员工，只是七牛用户）
4. 如果你只是想吐槽... 那么这可能也不是一个很好的地方，我觉得

**Comment by netroby** [comment]
@sofish  搜索部分的代码何在，我看看能不能帮忙改进搜索。

**Comment by netroby** [comment]
是不是这个 https://github.com/staticfile/api/blob/master/routes/api.js

**Comment by sofish** [comment]
@netroby 对的 :+1:

**Comment by ikbear** [comment]
@sizhang @netroby 我会改进这个搜索体验，谢谢你们的反馈。
