### ISSUE TITLE
Lodash 库只有 2.4.1 及之前版本

### ISSUE THREAD

**Issue by BiosSun** [staticfile/static#251]
目前 lodash 的最新版本是 3.8.0，在 cdnjs 中也已有该版本的相关配置；但在我们的官方首页进行搜索时，得到的搜索结果中显示最新版仅为 2.4.1，直接修改文件 URL 访问 3.8.0 版本也提示没有相关文件。

![image](https://cloud.githubusercontent.com/assets/2755933/7449373/759f5f6e-f267-11e4-8840-b04bf7cd6430.png)

![image](https://cloud.githubusercontent.com/assets/2755933/7449381/a5e32c0a-f267-11e4-962f-ec751d056431.png)

**Comment by meteormatt** [comment]
需要更新了

**Comment by Xuanwo** [comment]
咳，根据我对build脚本的观察，我合并了PR之后，还需要有人在服务器上执行那个build脚本之后才能将资源加入CDN。所以，目前为止，即使我更新了cdnjs，七牛那边的资源依然没有更新。

我已经给七牛那边发了邮件，希望服务器上可以添加一个webhook，方便自动更新啥的- -

**Comment by Cweili** [comment]
@Xuanwo 目前网站上的还是没有更新

**Comment by Xuanwo** [comment]
= =，服务器在七牛手里，我只能管Github这边啊= =

**Comment by meteormatt** [comment]
唉. 7牛的人到现在都没放权吗?
看来没必要继续用`staticfile`了

**Comment by Xuanwo** [comment]
updated
