### ISSUE TITLE
Amaz-UI已经更新很久了求更新

### ISSUE THREAD

**Issue by The-0** [staticfile/static#252]
已更新至2.3！！！
官方网站：
http://amazeui.org/download?ver=2.3.0

**Comment by Xuanwo** [comment]
你可以提交一个PR，我会尽快审核的

**Comment by minwe** [comment]
貌似没有和 CDNJS 同步，CDNJS 上有的内容这边都没有。

https://github.com/cdnjs/cdnjs/tree/5d4b0c2f56665ed151fcae280adeda473b540c12/ajax/libs/amazeui

**Comment by minwe** [comment]
@The-0 

http://amazeui.org/getting-started#shi-yong-cdn

可以使用官方提供的 CDN，现在使用的也是七牛的云存储。

staticfile 缺乏 CDNJS 的自动获取更新机制，每次更新都要 PR 的话略麻烦。

其实只要能定期把 CDNJS 同步过来就好了。

**Comment by Xuanwo** [comment]
updated
