### ISSUE TITLE
Twitter-Bootstrap 在 HTTPS 下返回 404

### ISSUE THREAD

**Issue by kinosang** [staticfile/static#257]
例如 `https://dn-staticfile.qbox.me/twitter-bootstrap/3.3.1/css/bootstrap.min.css`

返回 `{"error":"Document not found"}`

**Comment by JokerQyou** [comment]
UIKit 的资源文件也是同样的情况，ref #11

**Comment by Xuanwo** [comment]
确实如此

**Comment by Xuanwo** [comment]
已经修复了~
