### ISSUE TITLE
frozenui lib 搜索不到？

### ISSUE THREAD

**Issue by miaotmac** [staticfile/static#276]
hi，你好，请问下我的pr #274，在merge完后我在 http://staticfile.org/ 上面输入 frozenui 搜索不到，是什么原因呢？

**Comment by Xuanwo** [comment]
七牛那边没有更新

**Comment by miaotmac** [comment]
请问下七牛那边一般多久更新，有什么方法可以通知他们吗？

**Comment by Xuanwo** [comment]
七牛正在准备重建staticfile，貌似还在筹备中，所以最近一段时间可能都不会更新了。

**Comment by miaotmac** [comment]
奥奥。。。那怎么整。。。

**Comment by Xuanwo** [comment]
目前还在和七牛协商，我会努力让staticfile尽快回复运作
