### ISSUE TITLE
HTTPS方式引用无法使用

### ISSUE THREAD

**Issue by bluedarker** [staticfile/static#280]
HTTPS方式引用有问题,证书不受信任.
对于https站点无法使用http的方式引用js库,使用https方式浏览器将报安全错误导致无法加载.

**Comment by CoolSpring8** [comment]
#25 ...

**Comment by Xuanwo** [comment]
这个问题，我将会和七牛协商，在解决方案出来之前，请先使用别的替代方案，谢谢~
