### ISSUE TITLE
cdnjs上有的库本站没有的，如何添加到本站

### ISSUE THREAD

**Issue by Centaur** [staticfile/static#283]
在文档里看到本站的国外源同步自cdnjs，但是发现有些cdnjs上有的库在本站找不到。如果要将这些库加到本站，也必须象[这里](http://staticfile.org/about.html#howto)说的一样操作吗？

**Comment by Xuanwo** [comment]
目前我基本上会保持每天从cndjs同步一次
、
具体到服务器上何时更新，我还在跟七牛协调
