### ISSUE TITLE
twemoji 更新请求

### ISSUE THREAD

**Issue by lgh06** [staticfile/static#297]
cdnjs上现在已是1.4.2，从1.0.0到1.4.2中间隔了好几十个版本……其实我想问的是，从cdnjs同步，必须这个repo的管理员手动更新么……

**Comment by Xuanwo** [comment]
更新脚本年久失修，正在修复中，一旦确认没有问题将会正式运行~

**Comment by Xuanwo** [comment]
已经修复了~
