### ISSUE TITLE
"Document not found"

### ISSUE THREAD

**Issue by jingweizheng** [staticfile/static#299]
很奇怪，今天一直是"Document not found"，别家的静态文件都ok，咋回事？

**Comment by Xuanwo** [comment]
最近我们正在调试Staticfile的更新脚本，所以短时间会出现404的异常，我们会尽快修复~

**Comment by jingweizheng** [comment]
这个不是短时间啊，整整一天了！！！提前说一声嘛，早有防备。

**Comment by Xuanwo** [comment]
你好，现在应该已经Fix了，如果有个别的库无法访问，请另开issues~

**Comment by jingweizheng** [comment]
打不开，你们先自己试试，多测试几个节点看看吧。我用自己的七牛了，稳定性很重要，虽然是公益项目，但是不稳定信任度大打折扣呢
