### ISSUE TITLE
Document not found

### ISSUE THREAD

**Issue by jingweizheng** [staticfile/static#300]
http://cdn.staticfile.org/twitter-bootstrap/4.0.0-alpha/css/bootstrap.css

 TWITTER-BOOTSTRAP 4.0.0-alpha 全军覆没。。。

**Comment by Xuanwo** [comment]
脚本还是有问题- -

**Comment by Xuanwo** [comment]
脚本测试成功之后重新执行了qrsync， 文件量比较大，至今还在同步中，再等等吧。
以后速度就不会这么慢了~

**Comment by Xuanwo** [comment]
@jingweizheng TWITTER-BOOTSTRAP已经可以正常访问了，理论上来讲，这个脚本应该跑完了
