### ISSUE TITLE
首页怎么不出现默认的库了，搜索后也不出结果

### ISSUE THREAD

**Issue by iamziyue** [staticfile/static#305]
换了多个浏览器都这样，前几天还是好好的。

**Comment by Xuanwo** [comment]
唔- -，搜索api又挂了

**Comment by thkdog** [comment]
还挂着？。。尼玛

**Comment by MyTHo0O** [comment]
无法搜索是bug吗，而且还没有了默认展示的框架了

**Comment by Xuanwo** [comment]
这个已经Fix了。

**Comment by Yemsheng** [comment]
搜索 api http://api.staticfile.org/v1/search?q=jquery 的返回值 {"success":false,"error":{"code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect"}}

**Comment by Xuanwo** [comment]
@Yemsheng @thkdog  @MyTHo0O @iamziyue 已经Fix了~
