### ISSUE TITLE
首页搜索太卡了，非常需要优化

### ISSUE THREAD

**Issue by hojas** [staticfile/static#308]

**Comment by netfishx** [comment]
同上，基本处于不可用状态了

**Comment by quentinzhang** [comment]
同上，本来是非常好的服务，但首页的搜索功能做的也太差了，完全没考虑到性能，而且也不精准，继续改进！

**Comment by pentie** [comment]
还不如直接列表目录呢……起码可以查得到

**Comment by dsh0416** [comment]
确实，现在的搜索甚至都不是精确匹配的。。。还不如列个目录 Ctrl+F 搜一下

**Comment by fuzhaohao** [comment]
我还以为是我一个人的问题。

**Comment by Xuanwo** [comment]
抱歉，我们采用的ES搜索引擎方案比较糟糕，正在考虑更好的方案，如果有建议可以直接在本issues下回复。

首先直接列出目录不太合适，因为库的数量实在太多了。

**Comment by Xuanwo** [comment]
Fixed.
