### ISSUE TITLE
首页非常卡，chrome浏览器崩溃

### ISSUE THREAD

**Issue by xiangtao123** [staticfile/static#309]
进入首页特别慢，且浏览器崩溃。必须解决，现在处于不能用状态

**Comment by sinkcup** [comment]
现在首页空白了……

**Comment by Xuanwo** [comment]
= =，我这里看是正常的啊。。

**Comment by sinkcup** [comment]
卡在 ghbtns.com 的请求上

**Comment by xiangtao123** [comment]
google chrome v31.0.1650.57

![1](https://cloud.githubusercontent.com/assets/3273673/12449304/3eb811c6-bfb7-11e5-9a50-00f2950faf28.png)
![2](https://cloud.githubusercontent.com/assets/3273673/12449303/3eb49136-bfb7-11e5-879f-7c7b0b70e4cd.png)

**Comment by TechQuery** [comment]
|  项目       | 配置                                       |
|:------------:|:--------------------------------------:|
|  CPU       |  Intel Core  i5-4460  3.2GHz  |
|  Memory  |  8 GB                                     |
|  SSD       |  128 GB                                  |
|  OS         |  Windows 7  SP1  64-bit         |
| Browser  |  Google Chrome  v46             |

一开 StaticFile.Org 就卡爆，700+ MB 内存就没了…… 再点点贵站的页面 或 搜搜开源库，贵站主页所在选项卡就直接提示 Crash……

**Comment by Xuanwo** [comment]
Fixed.
