### ISSUE TITLE
是否考虑实现库的自动更新

### ISSUE THREAD

**Issue by amio** [staticfile/static#313]
人力拷贝很难保证跟得上库的最新版本
是不是考虑下做个自动更新的功能？从 npm、github 上拉取最新代码和版本

**Comment by longbai** [comment]
这个可以考虑，每隔一段时间去爬一下

**Comment by cocody** [comment]
不是说同步cdnjs么?jQuery 3.0 都没有?

**Comment by iwillwen** [comment]
@cocody 已经同步最新版了。

**Comment by TechQuery** [comment]
@iwillwen 并没有啊 —— http://www.bootcdn.cn/jquery/

**Comment by Xuanwo** [comment]
Fixed.
