### ISSUE TITLE
jquery版本落后7个版本，这个cdn不更新了吗？

### ISSUE THREAD

**Issue by cers000** [staticfile/static#318]
RT

**Comment by wpcfan** [comment]
你可以fork之后自己更新，然后提交一个pull request就行了

**Comment by TechQuery** [comment]
@wpcfan 这个 CDN 不是首先同步 cdnjs.com 的吗？

**Comment by Xuanwo** [comment]
Fixed.

**Comment by TechQuery** [comment]
@Xuanwo jQuery 版本并未更新啊，这个 Issue 没修复啊……

**Comment by Xuanwo** [comment]
七牛的工程师 @iwillwen 正在实现自动更新，可能还需要一段时间，自动更新测试OK之后再Close吧。
@TechQuery 多谢反馈

**Comment by iwillwen** [comment]
done
