### ISSUE TITLE
首页打开和搜索非常非常卡或失败，api.staticfile.qiniu.io挂了？

### ISSUE THREAD

**Issue by firesh** [staticfile/static#327]

**Comment by firesh** [comment]
我放弃了，换bootcss了，查个库的地址很费劲，卡死你，https路径不友好，今天首页都打不开。

**Comment by Xuanwo** [comment]
服务器出现了故障，正在修复。

firesh <notifications@github.com>于2016年4月16日周六 下午1:25写道：

**Comment by cocody** [comment]
bootcss 也很卡，如果你找到地址，这个cdn速度还是挺不错的。

**Comment by Xuanwo** [comment]
Fixed.

**Comment by firesh** [comment]
终于修复了。 我都不敢用了，还是用自己的地址保险。

**Comment by cocody** [comment]
太差了, 那么久才修复,其实这个问题存在很久了
