### ISSUE TITLE
staticfile.org无法使用

### ISSUE THREAD

**Issue by skyupward** [staticfile/static#337]
### 首页[http://staticfile.org/](http://staticfile.org/)    @进入报错：

[http://api.staticfile.qiniu.io/v1/popular](http://api.staticfile.qiniu.io/v1/popular)
```json
{"success":false,"error":{"code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect"}}
```

### 搜索JQuery：

[http://api.staticfile.qiniu.io/v1/search?q=JQuery](http://api.staticfile.qiniu.io/v1/search?q=JQuery)
```json
{"success":false,"error":{"code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect"}}
```

**Comment by cipchk** [comment]
没人维护了吗？哎……

**Comment by Xuanwo** [comment]
有人在维护的，不过最近七牛负责跟我对接的同学比较忙，所以没有时间重新开发新的搜索后端，非常抱歉

**Comment by Xuanwo** [comment]
Fixed.
