### ISSUE TITLE
主页的搜索不能用了

### ISSUE THREAD

**Issue by xtuer** [staticfile/static#373]
如下错误提示
Fetch API cannot load https://api.staticfile.org/v1/popular. No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by Xuanwo** [comment]
目前七牛的工程师正在重构整个服务，抱歉不能正常提供服务，如果知道具体的库和版本，你可以通过这种形式访问：  `https://cdn.staticfile.org/<libname>/<version>/<filename>`

**Comment by iwillwen** [comment]
done
