### ISSUE TITLE
建议开启从cdnjs.com同步，cdnjs提供了收录仓库

### ISSUE THREAD

**Issue by ian4hu** [staticfile/static#375]
[cdnjs/cdnjs](https://github.com/cdnjs/cdnjs) 提供了比较全面的收录，而且直接同步不是可以节省管理成本么

如果有cdnjs没有收录的，这边也可以手动收录的

**Comment by Xuanwo** [comment]
目前就是这样的，只不过cdnjs的目录现在对外部不可见。

**Comment by ian4hu** [comment]
但我发现react-redux这个在cdnjs上有，但是在static上没有，这是为什么？

**Comment by ian4hu** [comment]
还有 redux

**Comment by Xuanwo** [comment]
Ref #313 , #373 
目前七牛的工程师正在重构后端的代码，所以短时间内不能正常提供服务，自动更新也暂时没有开启。

**Comment by ian4hu** [comment]
OK

**Comment by iwillwen** [comment]
Done
