### ISSUE TITLE
https://www.staticfile.org/ 搜索不到KindEditor

### ISSUE THREAD

**Issue by ACTom** [staticfile/static#382]
libs中已经有KindEditor，https://cdn.staticfile.org/KindEditor/4.1.10/kindeditor.js 也能访问，但是https://www.staticfile.org/ 的项目搜索找不到KindEditor

**Comment by Xuanwo** [comment]
已复现，确认为BUG

**Comment by Xuanwo** [comment]
staticfile有，但是cdnjs没有的库无法通过项目搜索找到 @iwillwen

**Comment by iwillwen** [comment]
已修复。
