### ISSUE TITLE
No content-type when request a JavaScript file

### ISSUE THREAD

**Issue by dsonet** [staticfile/static#397]
Like visist https://cdn.staticfile.org/vue/2.1.3/vue.common.js,  doesn't set the content-type.

**Comment by ikbear** [comment]
<img width="894" alt="screenshot 2016-11-27 17 10 16" src="https://cloud.githubusercontent.com/assets/232018/20647044/6eaa0512-b4c4-11e6-91dc-b2d6d11d7ab2.png">

**Comment by dsonet** [comment]
Ya, I see it now.
