### ISSUE TITLE
首页加载错误

### ISSUE THREAD

**Issue by isLishude** [staticfile/static#436]
![image](https://cloud.githubusercontent.com/assets/24730006/26583138/94c2c7e6-4576-11e7-9341-7f5a1313bc32.png)

**Comment by isLishude** [comment]
如果不维护了，那建议大家使用 https://cdn.baomitu.com/ 吧

**Comment by doxiaodong** [comment]
@isLishude  你们这个更新不同步啊
例如： https://cdn.baomitu.com/crypto-js
https://cdnjs.com/libraries/crypto-js
