### ISSUE TITLE
cdn.staticfile.org HTTPS域名证书过期了

### ISSUE THREAD

**Issue by wisecrmgh** [staticfile/static#538]
赶紧换一下吧，国内CDN真的是不靠谱。

**Comment by cnwzhjs** [comment]
似乎被替换成了1个17年10月到期的证书

**Comment by cnwzhjs** [comment]
![image](https://user-images.githubusercontent.com/2706044/59617428-ebc1b180-9158-11e9-9571-2966ef3b6db6.png)

不过现在恢复了

![image](https://user-images.githubusercontent.com/2706044/59617464-fb40fa80-9158-11e9-8bb4-434618f930f4.png)
