### ISSUE TITLE
cdn挂了

### ISSUE THREAD

**Issue by llh1187** [staticfile/static#560]
![image](https://user-images.githubusercontent.com/40154001/68273184-b59db380-00a0-11ea-92eb-f63e5dab8280.png)
如图所示。

**Comment by llh1187** [comment]
<script src="https://cdn.staticfile.org/babel-standalone/6.26.0/babel.min.js"></script>

**Comment by wujingquan** [comment]
同，我刚的也遇到了，上来看看上面情况。

**Comment by feik** [comment]
2019/11/6   怎么又挂了啊

**Comment by absatu** [comment]
一旦挂了影响业务啊，在恢复之前，大家都怎么应对的？

**Comment by jzsn2018** [comment]
> 一旦挂了影响业务啊，在恢复之前，大家都怎么应对的？

换一个

**Comment by feik** [comment]
https://cdnjs.cloudflare.com/

**Comment by jia58960** [comment]
> https://cdnjs.cloudflare.com/

老哥，这个稳吗？
