### ISSUE TITLE
 为什么搜不出qiniu.js

### ISSUE THREAD

**Issue by aszx0413** [staticfile/static#572]
空间还是七牛提供的。在 libs 里面看到有，但是在网站上搜不出来

**Comment by aszx0413** [comment]
已经变成僵尸项目了吗

**Comment by aszx0413** [comment]
@ikbear @iwillwen 可以解答一下吗

**Comment by aszx0413** [comment]
好希望能有人来告诉我：不知道，也不会解决。好让我死了这条心

**Comment by aszx0413** [comment]
T.T

**Comment by xyjincan** [comment]
https://cdn.staticfile.org/qiniu-js/2.5.5/qiniu.min.js ?

**Comment by aszx0413** [comment]
> https://cdn.staticfile.org/qiniu-js/2.5.5/qiniu.min.js ?

感谢，但是为什么在官网搜索不出来
