### ISSUE TITLE
服务好像出问题了 2020年4月1日

### ISSUE THREAD

**Issue by jcyrss** [staticfile/static#574]
很多资源都访问不了了，比如
```py
https://cdn.staticfile.org/jquery/3.4.1/jquery.min.js 
```

![image](https://user-images.githubusercontent.com/10496014/78137928-b0c70b00-7458-11ea-8bba-c4c54c946eab.png)

**Comment by AndyLee1024** [comment]
https://cdn.staticfile.org/ 无法访问
