### ISSUE TITLE
请添加 `htmx`

### ISSUE THREAD

**Issue by dantezhu** [staticfile/static#648]
[Htmx](https://github.com/bigskysoftware/htmx)

> htmx is a library that allows you to access modern browser features directly from HTML, rather than using javascript.

**Comment by felixonmars** [comment]
<img width="732" alt="image" src="https://github.com/staticfile/static/assets/1006477/14f52bbf-c2cc-4cbb-9a1a-12eb29580193">

It's already present. The search box is a little bit strange though.
