### ISSUE TITLE
求添加前端框架JS css

### ISSUE THREAD

**Issue by cgq1777** [staticfile/static#658]
框架官网：http://www.layui-vue.com/zh-CN/index

添加的框架

https://unpkg.com/@layui/layui-vue@2.9.1/umd/index.js

https://unpkg.com/@layui/layui-vue@2.9.1/lib/index.css

https://unpkg.com/vue@3.3.4/dist/vue.global.js

**Comment by DMaxProfile** [comment]
layui 已经在里面
![layui](https://github.com/staticfile/static/assets/141997291/657a1bae-90a9-48fc-96e4-9a4730a0daa6)
