### ISSUE TITLE
CDN缓存错误缓存了CORS响应头

### ISSUE THREAD

**Issue by Cweili** [staticfile/static#662]
特别是由于多缓存了 allow-origin，导致其他域名无法跨域请求这个资源了
![Snipaste_2023-12-11_17-18-18](https://github.com/staticfile/static/assets/2128450/82fe9588-f053-4335-9282-bfac826aa1a3)

**Comment by Cweili** [comment]
@iwillwen 可以看下这个bug吗

**Comment by zeplios** [comment]
+1

**Comment by zzzqu** [comment]
+1

**Comment by gqk** [comment]
+1

**Comment by chettestwef** [comment]
+1
![image](https://github.com/staticfile/static/assets/99162086/94bbd509-c780-467c-9b22-39ca7e745e75)
![image](https://github.com/staticfile/static/assets/99162086/55514327-4a49-4158-b814-6aef6e9b1ea0)

**Comment by jrotty** [comment]
+1，我也是字体图标寄了

**Comment by yinbug** [comment]
也是出现这个问题了，怎么回事？被黑了吗？

**Comment by LengYXin** [comment]
+1
![image](https://github.com/staticfile/static/assets/19631404/74e6bb76-8adc-4ff7-97a2-1a124072ecec)

**Comment by Alien-Lai** [comment]
![image](https://github.com/staticfile/static/assets/17607954/6ebf823f-6040-45cd-958b-691000cc62c5)

https://cdn.staticfile.org/element-ui/2.15.0/theme-chalk/fonts/element-icons.ttf
https://cdn.staticfile.org/element-ui/2.15.0/theme-chalk/fonts/element-icons.woff

**Comment by DTZHY** [comment]
+1  cdn资源报跨域

**Comment by zhfanrui** [comment]
+1

**Comment by ikechan8370** [comment]
+1

**Comment by iTGG666** [comment]
是不是被黑了，全是些毫无关联的请求
![微信截图_20231212184022](https://github.com/staticfile/static/assets/94790128/1ecd8332-cd5a-4e44-8ee4-b838cb514412)

**Comment by xqdoo00o** [comment]
看起来这些源域名都有引用对应的资源的

**Comment by ShenJieXin** [comment]
+1

**Comment by ShenJieXin** [comment]
+1

**Comment by leon-kfd** [comment]
一样字体文件会出现跨域

**Comment by bennkwok** [comment]
希望能赶紧解决啊，全都用不了了

**Comment by taoso** [comment]
我的博客也无法正常加载 web 字体了 😢 
https://taoshu.in/

**Comment by leakeung** [comment]
![121506](https://github.com/staticfile/static/assets/13065657/248663b8-9c14-46e2-b336-75d90b8caeef)

what happen?

**Comment by leon-kfd** [comment]
可临时将`https://cdn.staticfile.org`切换到`https://cdnjs.cloudflare.com/ajax/libs/`或者`https://cdnjs.loli.net/ajax/libs/` 都是同源于`cdnjs`

**Comment by mycpen** [comment]
+1，字体文件报错

![image-20231213193058571](https://github.com/staticfile/static/assets/72154342/005b3c02-6b09-419a-a295-967d5e23d257)

**Comment by Pil0tXia** [comment]
同样遇到此问题。问题页面：https://www.pil0txia.com/

**Comment by Andy-Chuck** [comment]
看来不是我一个人遇到这个问题了
![1](https://github.com/staticfile/static/assets/54295429/3ce58cb2-db29-4166-b43c-42b40fac54d1)

**Comment by argvchs** [comment]
![image](https://github.com/staticfile/static/assets/64528288/e7387d1f-f178-4d52-8537-97b2bbfb751e)

**Comment by littleyz** [comment]
+1

**Comment by xuanzhi33** [comment]
+1

**Comment by bianyukun1213** [comment]
同样遇到了这个问题。

**Comment by cikheo** [comment]
同样遇到此问题,什么时候能解决
![image](https://github.com/staticfile/static/assets/92386948/60282aad-94bc-4e4f-9cdb-44c2419d826b)

**Comment by mfkvfn** [comment]
4天都解决不了。七牛云技术这么差的吗？

**Comment by taoso** [comment]
> 4天都解决不了。七牛云技术这么差的吗？

免费的公益项目，要啥自行车？ @mfkvfn 如果觉得慢可以自建 CDN

**Comment by xqdoo00o** [comment]
> > 4天都解决不了。七牛云技术这么差的吗？
> 
> 免费的公益项目，要啥自行车？ @mfkvfn 如果觉得慢可以自建 CDN

这个不是慢，是没法用

**Comment by mfkvfn** [comment]
> > 4天都解决不了。七牛云技术这么差的吗？
> 
> 免费的公益项目，要啥自行车？ @mfkvfn 如果觉得慢可以自建 CDN

当然不是只要它的免费业务。它还有其它收费的业务。2023-08-09我们用的它的七牛云对象存储也出过问题。还出过域名备案过期的问题。你说你一SaaS云服务厂商，用的人那么多，你域名备案出问题，客户怎么办？

staticfile.org 也不是它第一次出问题了。基本上每2年会出一次大问题。百度查下一大堆。所以也就只能是自己不太重要的小项目用一用。正确的对外正式项目要慎重。

这给人一种公司技术不行的感觉。这样的话以后你选择它的收费业务时是不是考虑考虑。
做对外业务最怕名声不好，一般有问题都是第一时间解决。这个虽然是免费的，要是不想好好服务，还不如直接关了，起码不会拖累公司名声。

**Comment by jackey20152011** [comment]
> > 4天都解决不了。七牛云技术这么差的吗？
> 
> 免费的公益项目，要啥自行车？ @mfkvfn 如果觉得慢可以自建 CDN

如果是东西少，或者是慢，或者是服务差，公益可以理解，大不了不用
但就算免费公益，被黑了不去解决，类似被人抽脸还不说话，就离谱

**Comment by jackey20152011** [comment]
> > 4天都解决不了。七牛云技术这么差的吗？
> 
> 免费的公益项目，要啥自行车？ @mfkvfn 如果觉得慢可以自建 CDN

就算是免费公益，但被黑了不去解决，就离谱

**Comment by Francklin** [comment]
可以试试www.webcache.cn
