### ISSUE TITLE
wrong content type for mjs

### ISSUE THREAD

**Issue by lexdene** [staticfile/static#663]
I got an error:

> Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "application/octet-stream". Strict MIME type checking is enforced for module scripts per HTML spec.

I think it is caused by the wrong content type of mjs by cdn.staticfile.org:

    $ curl -i https://cdn.staticfile.org/element-plus/2.4.3/index.full.mjs 2>/dev/null | grep -i content-type
    content-type: application/octet-stream

A simple way to reproduce this error:

    <!DOCTYPE html>
    <html>
      <body>
        <script type="module" src="https://cdn.staticfile.org/element-plus/2.4.3/index.full.mjs"></script>
      </body>
    </html>

**Comment by DMaxProfile** [comment]
issue fixed:
https://cdn.staticfile.org/element-plus/2.4.3/index.full.mjs
sorry for inconvenient

**Comment by lexdene** [comment]
this error happens again.

    $ curl -i https://cdn.staticfile.org/element-plus/2.4.3/index.full.mjs 2>/dev/null | grep -i ^content-type
    content-type: application/octet-stream

also after I use staticfile.net:

    $ curl -i https://cdn.staticfile.net/element-plus/2.4.3/index.full.mjs 2>/dev/null | grep -i ^content-type
    content-type: application/octet-stream

@boon755

**Comment by DMaxProfile** [comment]
issue fixed
![1](https://github.com/staticfile/static/assets/141997291/e483a337-fa89-45aa-b852-af541de70695)

**Comment by lexdene** [comment]
This error happens again on some specific nodes.

For example, if I resolve `cdn.staticfile.net` to `218.92.135.49`, it is correct:

    $ curl -i --compressed 'https://cdn.staticfile.net/element-plus/2.3.14/index.full.mjs' \
        --resolve cdn.staticfile.net:443:218.92.135.49 \
        2>/dev/null | grep -i ^content-type
    content-type: application/javascript

But for `111.14.190.66`, it is abnormal:

    $ curl -i --compressed 'https://cdn.staticfile.net/element-plus/2.3.14/index.full.mjs' \
        --resolve cdn.staticfile.net:443:111.14.190.66 \
        2>/dev/null | grep -i ^content-type
    content-type: application/octet-stream

@boon755
