### ISSUE TITLE
CDN是被挂马了吗

### ISSUE THREAD

**Issue by jackey20152011** [staticfile/static#667]
![image](https://github.com/staticfile/static/assets/12571553/c7228ac3-31e7-4820-8f90-d021f72d6885)

![image](https://github.com/staticfile/static/assets/12571553/e63c1184-0018-4eb7-b701-44f6fed06c52)

**Comment by mfkvfn** [comment]
是的。而且4天都没解决掉。
估计这公司技术不行。以后不敢用它家的七牛云产品了。简直影响正常业务。

**Comment by jackey20152011** [comment]
> 是的。而且4天都没解决掉。 估计这公司技术不行。以后不敢用它家的七牛云产品了。简直影响正常业务。

因为这事，已经将 js 都本地化了，靠山山倒，还是得靠自己啊

**Comment by Andy-Chuck** [comment]
#662

**Comment by XYZ109** [comment]
是的，都是CORS错误

**Comment by DMaxProfile** [comment]
非常抱歉给您造成不便，目前问题已得到妥善处理。
