### ISSUE TITLE
是不是节点挂了

### ISSUE THREAD

**Issue by shadowmas** [staticfile/static#669]
苏州、杭州、上海访问出现下列情况
![image](https://github.com/staticfile/static/assets/30276739/821884f5-6f74-412d-a81c-d4141c9e821c)
![image](https://github.com/staticfile/static/assets/30276739/88133a8b-58be-4349-bbc0-62e6461e1385)

**Comment by gaojunshan** [comment]
cdn 挂掉了，这个开源库应该是不维护了，建议存本地。
![Snipaste_2023-12-16_19-54-01](https://github.com/staticfile/static/assets/24838653/73f2e154-e659-4a0c-a4ef-8f25a440e051)

**Comment by jiayp** [comment]
> 建议存本地。

这是哪儿看到的？

**Comment by DMaxProfile** [comment]
非常抱歉给您造成不便，目前问题已得到妥善处理。
