### ISSUE TITLE
cdn加速服务是不是挂了

### ISSUE THREAD

**Issue by 709343767** [staticfile/static#670]
cdn加速服务是不是挂了，直接502

**Comment by 444722146** [comment]
俺也一样，现在好了

**Comment by 709343767** [comment]
这是来自QQ邮箱的假期自动回复邮件。 您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by DMaxProfile** [comment]
非常抱歉给您造成不便，目前问题已得到妥善处理。
