### ISSUE TITLE
CDN挂了吗？北京访问不正常

### ISSUE THREAD

**Issue by jiayp** [staticfile/static#671]
加载不了第三方库了

**Comment by jiayp** [comment]
现在恢复了，最近CDN很不稳定啊。咱们后面还运营吗？

**Comment by flymorn** [comment]
[这里有帖子回复说不维护了](https://github.com/staticfile/static/issues/669)

**Comment by DMaxProfile** [comment]
非常抱歉给您造成不便，目前问题已得到妥善处理。
