### ISSUE TITLE
Failed to decode downloaded font:

### ISSUE THREAD

**Issue by mr-zxd** [staticfile/static#673]
Failed to decode downloaded font: https://cdn.staticfile.org/layui/2.9.2/font/iconfont.woff2?v=282
OTS parsing error: Failed to convert WOFF 2.0 font to SFNT
Failed to decode downloaded font: https://cdn.staticfile.org/layui/2.9.2/font/iconfont.woff?v=282
OTS parsing error: incorrect file size in WOFF header
Failed to decode downloaded font: https://cdn.staticfile.org/layui/2.9.2/font/iconfont.ttf?v=282
OTS parsing error: 0GSU: invalid table offset

**Comment by mycpen** [comment]
同上，字体报错

![image-20231227103134848](https://github.com/staticfile/static/assets/72154342/5e7504c8-4141-4624-9c9c-f8501f68c9dc)
![image-20231227103157751](https://github.com/staticfile/static/assets/72154342/f87eee81-66a7-4b10-81b9-7eea43e979ad)

**Comment by lbyxiaolizi** [comment]
I have the same problem

**Comment by zzzqu** [comment]
+1，好久了

**Comment by DMaxProfile** [comment]
已处理，请清除缓存。
