### ISSUE TITLE
字体文件提示下载失败

### ISSUE THREAD

**Issue by WuYunlong** [staticfile/static#674]
在使用fontAsome 或者element-ui 这些带有字体的时候浏览器报错
如下图

<img width="860" alt="image" src="https://github.com/staticfile/static/assets/3301446/94240367-510f-4970-b21a-277426e1215b">

Failed to decode downloaded font: https://cdn.staticfile.org/element-ui/2.15.7/theme-chalk/fonts/element-icons.woff
OTS parsing error: incorrect file size in WOFF header
Failed to decode downloaded font: https://cdn.staticfile.org/element-ui/2.15.7/theme-chalk/fonts/element-icons.ttf
OTS parsing error: 0GSU: misaligned table

**Comment by DMaxProfile** [comment]
测试了没问题
https://jsbin.com/pocuhafaje/edit?html,output
清除你的缓存看看。
