### ISSUE TITLE
当前CDN是否有节点状态异常？

### ISSUE THREAD

**Issue by mzlogin** [staticfile/static#677]
我这边引用了 <https://cdn.staticfile.org/layui/2.9.2/layui.js>

发现请求都会打到 `111.170.131.61` 这个 IP，但是刷新页面，有时返回正常，有时返回 404。

<img width="265" alt="image" src="https://github.com/staticfile/static/assets/1646590/195b078a-a0eb-471b-98d4-c5230c9095f7">

**Comment by wwlwwww** [comment]
https://cdn.staticfile.net/jquery/3.7.1/jquery.min.js

JQuery也一样，超时严重，不知道什么时候开始的；17ce测出来的也大多节点是超时

**Comment by wwlwwww** [comment]
![image](https://github.com/staticfile/static/assets/3937045/f7fa678e-04fb-4084-8775-4f0b095ba991)
官网API也超时

**Comment by jason1235** [comment]
+1今天凌晨开始的，好像现在恢复了

**Comment by houseme** [comment]
> ![image](https://private-user-images.githubusercontent.com/3937045/294973273-f7fa678e-04fb-4084-8775-4f0b095ba991.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3ODQzNTUsIm5iZiI6MTcwNDc4NDA1NSwicGF0aCI6Ii8zOTM3MDQ1LzI5NDk3MzI3My1mN2ZhNjc4ZS0wNGZiLTQwODQtODc3NS00ZjBiMDk1YmE5OTEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDlUMDcwNzM1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGVjYzczOWMyMTA2MzQwMjU0ODI3NzRhYWIyOTI3OGY5NzFiZjI2Njc2MDRmMzc1MjMyMjM5MGVkNjIyOGVmNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.-uoB0iJov3tTe-XjeLjKa208fyuqXRkMjbPxze5tAyk) 官网API也超时

这个情况还是存在

**Comment by myrandy** [comment]
我测速，全国标红。

**Comment by ZYGLQexplorer** [comment]
![image](https://github.com/staticfile/static/assets/66054495/8c7edea9-110c-4c88-b4f7-362b96b93411)

**Comment by myrandy** [comment]
![微信截图_20240111104136](https://github.com/staticfile/static/assets/3240794/31269e02-23b4-4e1d-ba94-c43456c34f7c)

七牛慎用，不提供服务，通知也不发。

**Comment by flydo** [comment]
@sorcerer-ma 麻烦在首页添加一个警示停止维护的公告。

**Comment by DMaxProfile** [comment]
![1](https://github.com/staticfile/static/assets/141997291/d3bdb522-65fb-417e-a36d-9149fd68411c)
目前正常
