### ISSUE TITLE
请求更新naive-ui cdn版本至最新版本2.37.3

### ISSUE THREAD

**Issue by XiaoDaiGua-Ray** [staticfile/static#678]
# 请求更新 naive-ui cdn 版本至最新版本 2.37.3

当前 `naive-ui` 版本落后于最新版本，请求更新与最新的 `2.37.3` 版本。

**Comment by ZYGLQexplorer** [comment]
https://github.com/staticfile/static/issues/677#issuecomment-1886090827
已经不维护了，及时更换

**Comment by XiaoDaiGua-Ray** [comment]
感谢告知，谢谢

**Comment by DMaxProfile** [comment]
@XiaoDaiGua-Ray 已更新
![2](https://github.com/staticfile/static/assets/141997291/f7c05b67-f576-4522-bfe6-249eb121dfdb)
