### ISSUE TITLE
CDN里element-ui/2.12.0这个库坏了，麻烦帮忙处理一下

### ISSUE THREAD

**Issue by ToyotaLeee** [staticfile/static#679]
![微信图片_20240113150301](https://github.com/staticfile/static/assets/156501016/024d3249-fe1d-43e0-ac38-2eb417e3e025)

**Comment by ToyotaLeee** [comment]
https://cdn.staticfile.org/element-ui/2.12.0/index.js

**Comment by openlin** [comment]
遇到了同样的问题，换了cdn：https://unpkg.zhimg.com/element-ui@2.12.0/lib/index.js

**Comment by ZYGLQexplorer** [comment]
https://github.com/staticfile/static/issues/677#issuecomment-1886090827
已经不维护了，及时更换

**Comment by DMaxProfile** [comment]
@ToyotaLeee 已处理
![element-ui](https://github.com/staticfile/static/assets/141997291/eae8111d-ad2b-4260-b202-3463c027ce58)
