### ISSUE TITLE
staticfile.net中搜索不到一些开源项目，但在cdnjs是有的

### ISSUE THREAD

**Issue by xnx3** [staticfile/static#680]
您好，我的开源项目 https://gitee.com/mail_osc/translate 是放在了cdnjs 提交采纳大概有小半个月了吧，名字为  translate.js 
 在cdnjs.com 是能正常搜到的，但是在中国cdnjs的效果不太好，我想使用 staticfile 提供的cdn加速能力，但是我在 staticfile.net 中搜索不到，我看说明是每天同步一次cdnjs的信息，是不是同步出现了异常了呢？如下图   

![image](https://github.com/staticfile/static/assets/8872471/d8751b25-a5bc-437c-8a0b-86872d3fc14d)

另外这里的 CDNS 是不是写错了，是不是应该是 CDNJS ？

**Comment by xnx3** [comment]
在cdnjs.com 上是有的，而且已经存在小半个月了  
![image](https://github.com/staticfile/static/assets/8872471/474cbe17-5b57-45c7-a34a-8969670577d2)

**Comment by wsqstar** [comment]
v2上来的 听说停止维护了

**Comment by ZYGLQexplorer** [comment]
https://github.com/staticfile/static/issues/677#issuecomment-1886090827
已经不维护了，及时更换

**Comment by xnx3** [comment]
好的好的，非常感谢告知

**Comment by DMaxProfile** [comment]
@xnx3 技术人员会跟进。

**Comment by xnx3** [comment]
> @xnx3 技术人员会跟进。

我看有朋友说停止维护了，是指这个项目还继续进行持续维护及使用吗？那太好了

**Comment by Francklin** [comment]
可以试试www.webcache.cn

**Comment by DMaxProfile** [comment]
@xnx3 还有维护的

**Comment by DMaxProfile** [comment]
@xnx3 试试 https://cdn.staticfile.org/translate.js/2.11.0/translate.js

**Comment by xnx3** [comment]
> 可以试试www.webcache.cn

感谢

**Comment by xnx3** [comment]
> @xnx3 试试 https://cdn.staticfile.org/translate.js/2.11.0/translate.js

非常感谢！ 

> @xnx3 试试 https://cdn.staticfile.org/translate.js/2.11.0/translate.js

非常感谢！  如果我想对它进行自动更新呢？ 我在 cdnjs 上通过配置 packages.json ,可以在里面可以定义自动更新的目标仓库及版本，咱这个是要怎么进行自动更新呢？  另外我提交的pull https://github.com/staticfile/static/pull/665  我看也一直没消息，现在是可以用pull方式更新还是怎么更新呢？

**Comment by xnx3** [comment]
> @xnx3 试试 https://cdn.staticfile.org/translate.js/2.11.0/translate.js

我通过 https://api.staticfile.org/libraries/translate.js 看到了，维护更新这块看来应该是同步 cdnjs 的，没别的问题了，感谢老哥
