### ISSUE TITLE
字体文件使访问staticfile.org速度大大减慢

### ISSUE THREAD

**Issue by chbkqx** [staticfile/static#681]
![Screenshot_2024-01-16-18-40-40-549_mark via](https://github.com/staticfile/static/assets/130931908/f624d20e-6125-4b0a-8931-65165fa1d336)
在近几次访问时明显感觉此站的访问速度慢了好多，检查了一下网络日志，发现了一个ttf文件。
在网站中内联ttf文件，而且还是一个10m的ttf文件，这对于网络质量一般都访问者来说是个很大的压力，建议去除或选用较小包的字体。

**Comment by DMaxProfile** [comment]
技术处理中。抱歉对您造成了不便。

**Comment by DMaxProfile** [comment]
已处理
![font](https://github.com/staticfile/static/assets/141997291/b90a3402-8c8d-4ec2-a535-4dda440700a2)
