### ISSUE TITLE
查询出现http错误

### ISSUE THREAD

**Issue by e2lc5** [staticfile/static#682]
index-b2727113f449d9ff.js:1 Mixed Content: The page at 'https://www.staticfile.org/' was loaded over HTTPS, but requested an insecure resource 'http://api.staticfile.net/libraries/hexo-generator-searchdb'. This request has been blocked; the content must be served over HTTPS.

**Comment by ZYGLQexplorer** [comment]
https://github.com/staticfile/static/issues/677#issuecomment-1886090827
已经不维护了，及时更换

**Comment by DMaxProfile** [comment]
@e2lc5 sorry for the inconvenient, issue has been fixed
![fixed1](https://github.com/staticfile/static/assets/141997291/526828f4-4ba9-4da5-bde2-42df25c32bd7)

**Comment by e2lc5** [comment]
confirm fix, staticfile.org is a very useful cdn, consider donate from chinese mainland user
