### ISSUE TITLE
倒闭了吗？

### ISSUE THREAD

**Issue by monyuan** [staticfile/static#683]
也不发个公告

**Comment by veking** [comment]
只可意会不可言传，赶紧换吧。

**Comment by DMaxProfile** [comment]
网页正常操作
![static](https://github.com/staticfile/static/assets/141997291/c342d654-a288-4d03-9069-0863d6b4c2b2)

**Comment by ZYGLQexplorer** [comment]
> 网页正常操作 ![static](https://private-user-images.githubusercontent.com/141997291/298098999-c342d654-a288-4d03-9069-0863d6b4c2b2.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3MTIyMTksIm5iZiI6MTcwNTcxMTkxOSwicGF0aCI6Ii8xNDE5OTcyOTEvMjk4MDk4OTk5LWMzNDJkNjU0LWEyODgtNGQwMy05MDY5LTA4NjNkNmI0YzJiMi5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyMFQwMDUxNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NGYxNDNmNmUwMjg0ODFhMDAzOTM2NjZmMGRkMGJlODY3MzlhNzQ4Y2I0Mzg3ZDgzOTJiYzkwMzNiMWIwOTRiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.f1csfDTObV7aF46JInR7VvQ1dcr0UJelYgzYXI6wBTo)

![image](https://github.com/staticfile/static/assets/66054495/0319985d-4c49-4221-bbd7-8238b1732630)
