### ISSUE TITLE
网站语言选项问题

### ISSUE THREAD

**Issue by OSNewbie** [staticfile/static#684]
网站语言选项，你们好像弄反了 明明是英文页面变成中文，把英文界面变成中文，这个是个小错误

**Comment by OSNewbie** [comment]
网站首页显示介绍，有错别字，什么仓车？是仓库

仓车 改成仓库，要么改成，开源仓库
下面那个错别字也是，

开源车 

还有就是那个简介页面第一个字就错怎么是那个象 不应该是这个 像 还有那个结尾开源车改成开源仓库

**Comment by OSNewbie** [comment]
![20240121_131517](https://github.com/staticfile/static/assets/85106891/e654ebec-9fef-4baa-b792-05b0914e018e)

**Comment by OSNewbie** [comment]
>
![20240121_131520](https://github.com/staticfile/static/assets/85106891/a3b1ac27-a7f5-48fa-ab49-2778d6f895af)

**Comment by OSNewbie** [comment]
别人都看你笑话咯

**Comment by DMaxProfile** [comment]
谢谢提醒，技术会跟进

**Comment by DMaxProfile** [comment]
已更新
