### ISSUE TITLE
被墙了，无法访问，翻墙才能访问

### ISSUE THREAD

**Issue by nn1900** [staticfile/static#685]

**Comment by nn1900** [comment]
之前staticfile.org被墙了

**Comment by li151293** [comment]
直接访问地址可以，页面内引用有概率不行

**Comment by nn1900** [comment]
直接访问也不行，翻墙可以

**Comment by A-Circle-Zhang** [comment]
貌似是国内 CDN 节点遇到有 Referer 头的请求会挂住不响应，不是被墙。
不带 Referer 的请求（比如浏览器直接打开）就没问题。

**Comment by chang505004849** [comment]
是的，我们也遇到了,为什么会限制呢


> 貌似是国内 CDN 节点遇到有 Referer 头的请求会挂住不响应，不是被墙。 不带 Referer 的请求（比如浏览器直接打开）就没问题。

**Comment by lltx** [comment]
<img width="828" alt="image" src="https://github.com/staticfile/static/assets/50090230/bd7b76fd-eb52-4ae7-908c-354dea6caaaa">


先顶一下
```
    <meta name="referrer" content="no-referrer" />

```

**Comment by DMaxProfile** [comment]
我这边是可以访问的，有截图吗？方便提供给一下
![image](https://github.com/staticfile/static/assets/141997291/58e91261-11bd-450d-b1a2-d18c5f59fe77)

**Comment by reason211** [comment]
> 我这边是可以访问的，有截图吗？方便提供给一下 ![image](https://private-user-images.githubusercontent.com/141997291/298834270-58e91261-11bd-450d-b1a2-d18c5f59fe77.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwMDQzNDQsIm5iZiI6MTcwNjAwNDA0NCwicGF0aCI6Ii8xNDE5OTcyOTEvMjk4ODM0MjcwLTU4ZTkxMjYxLTExYmQtNDUwZC1iMWEyLWQxOGM1ZjU5ZmU3Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyM1QxMDAwNDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZmE0MmU0MjQ2NWI2NzM1MmUxZWQxZTYwYWIzMjhkOTg3YmZhZDQ0M2M3OTdlNDc2MDQwOTBhNDdhZGRhZDg4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.wqtahokQtgu-tTR133_sEXYSvV_095xjCMAO3D7pavk)

最近是有增加针对Referer的限流策略吗

**Comment by DMaxProfile** [comment]
@reason211 没有

**Comment by Exrick** [comment]
@boon755 限流加载疑似存在 部分CDN有概率需等待2分钟整加载成功 可复现
<img width="842" alt="image" src="https://github.com/staticfile/static/assets/22902934/c189f161-e488-45ab-88e0-a4335bca2316">
