### ISSUE TITLE
貌似是国内 CDN 节点遇到有 Referer 头的请求会挂住不响应，不是被墙。

### ISSUE THREAD

**Issue by Fishlz** [staticfile/static#686]
那应该怎么解决呢？

**Comment by DMaxProfile** [comment]
@Fishlz 有截图吗？方便提供给一下。

**Comment by reason211** [comment]
我还以为是故意限制不让我们用了🥲

**Comment by DMaxProfile** [comment]
![image](https://github.com/staticfile/static/assets/141997291/c0498304-280d-4905-9321-830f86ac3781)

我这边测试没问题。
