### ISSUE TITLE
Access-Control-Allow-Origin问题

### ISSUE THREAD

**Issue by net660** [staticfile/static#687]
看到官网提示 "受org域名备案影响主域名更新为 staticfile.net , org老域名不再维护请用户尽快更换为net。"
切换后net域名存在Access-Control-Allow-Origin问题，该问题在org时也存在，现在org域名貌似恢复了
我使用的是这两个资源均存在这个问题，
https://cdn.staticfile.net/twitter-bootstrap/3.3.7/css/bootstrap.min.css
https://cdn.staticfile.net/font-awesome/4.7.0/css/font-awesome.min.css
建议官方出个官方群聊方便问题的即使处理

**Comment by HJWqa** [comment]
我这里也是这样。
_Access to font at 'https://cdn.staticfile.net/mdui/1.0.2/fonts/roboto/Roboto-RegularItalic.woff' from origin 'https://stdb.pennote.cn' has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header contains multiple values '*, *', but only one is allowed._
GET https://cdn.staticfile.net/mdui/1.0.2/fonts/roboto/Roboto-RegularItalic.woff net::ERR_FAILED 200 (OK)

不过我这里css和js没问题，字体有问题

**Comment by net660** [comment]
我也是字体问题 太难受了

**Comment by HJWqa** [comment]
> 我也是字体问题 太难受了

我这里把css的链接改成了org，也算能暂时解决问题吧
前段时间（数月前）用着org域名的也出现过几次没有字体

**Comment by DMaxProfile** [comment]
.net 的域名也支持： Access-Control-Allow-Origin 
![x1](https://github.com/staticfile/static/assets/141997291/c45dcf36-f885-4558-aee1-acf5ecf32c8b)
![x2](https://github.com/staticfile/static/assets/141997291/455a2e6f-5672-47b4-a960-a9987097b019)
![x3](https://github.com/staticfile/static/assets/141997291/4357042f-960d-4370-806a-c6f0103d23b5)
浏览器:
![x4](https://github.com/staticfile/static/assets/141997291/80d65364-7e69-46ac-b01f-d1c74a836ea6)
建议清除缓存再访问看看。

**Comment by HJWqa** [comment]
可是，最直接的，使用mdui的网站，mdui的css引用使用的.org域名就正常，.net域名就不正常（指图标字体）
