### ISSUE TITLE
woff2字体文件跨域有问题

### ISSUE THREAD

**Issue by xiaoyanu** [staticfile/static#689]
https://cdn.staticfile.net/mdui/0.4.1/icons/material-icons/MaterialIcons-Regular.woff2
The 'Access-Control-Allow-Origin' header contains multiple values '*, *', but only one is allowed.
![QQ截图20240211212411](https://github.com/staticfile/static/assets/61397705/09aaba61-ae1c-459d-8fc8-3ee5a1a27aac)

**Comment by DMaxProfile** [comment]
这个不是我们的问题哦，你可以到这里看：
https://output.jsbin.com/yodusisane/1
![1](https://github.com/staticfile/static/assets/141997291/e890e802-c12b-4997-88bd-fd42c8bd0c48)
我们拿到的是 200
代码在这里
https://jsbin.com/yodusisane/1/edit?html,console,output

**Comment by xiaoyanu** [comment]
您的邮件我已经收到了~请耐心等待我的回复
