### ISSUE TITLE
.net域名的网址，woff2字体文件跨域报错，响应头字段重复

### ISSUE THREAD

**Issue by Leopard-C** [staticfile/static#690]
![image](https://github.com/staticfile/static/assets/42399105/6dc8a3f2-313b-46ea-b329-6d5037019aa4)

![image](https://github.com/staticfile/static/assets/42399105/e3284ca9-9a77-411f-8346-ae551e1ec52c)

```shell
curl https://cdn.staticfile.net/layui/2.5.7/font/iconfont.woff\?v\=256 -I
```

通过 `.org` 访问可以正常跨域，但是 `.net` 访问报错。

**Comment by DMaxProfile** [comment]
![2](https://github.com/staticfile/static/assets/141997291/d2acc118-fba5-4a5c-b882-cea8b6b7b1fc)
已修复
