### ISSUE TITLE
font-awesome无法引入，有跨域问题，能解决下吗，谢谢

### ISSUE THREAD

**Issue by lizhicheng** [staticfile/static#691]
localhost换成服务器网址还是一样有跨域问题，能解决下吗，谢谢

Access to font at 'https://cdn.staticfile.net/font-awesome/6.5.1/webfonts/fa-solid-900.woff2' from origin 'http://localhost' has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header contains multiple values '*, *', but only one is allowed.
fa-solid-900.woff2:1 
        
        
       Failed to load resource: net::ERR_FAILED
index.html:1 Access to font at 'https://cdn.staticfile.net/font-awesome/6.5.1/webfonts/fa-solid-900.ttf' from origin 'http://localhost' has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header contains multiple values '*, *', but only one is allowed.
fa-solid-900.ttf:1 
        
        
       Failed to load resource: net::ERR_FAILED

**Comment by DMaxProfile** [comment]
你好，检查了，我们这里没问题哦
![image](https://github.com/staticfile/static/assets/141997291/b75dd550-e4da-4a36-9ea9-7a20dda3210a)
测试站：
https://jsbin.com/loravebehe/edit?html,console,output
