### ISSUE TITLE
is:issue is:open 首页搜索框输入“x”，“x”字母被替换成了“.”

### ISSUE THREAD

**Issue by bfreely** [staticfile/static#692]
图中我输入的“xlsx”这四个字符，但是“x”替换成“.”了。

![微信截图_20240306153407](https://github.com/staticfile/static/assets/19866509/30d345a3-7604-4f43-869d-80ade9f51318)

**Comment by bfreely** [comment]
搜索出来的页面，“x”也被替换成“.”了

![微信截图_20240306154044](https://github.com/staticfile/static/assets/19866509/d5040d97-8e37-427d-a09f-5598a4e1608b)

**Comment by vincent-backend** [comment]
this issue is fixed
![image](https://github.com/staticfile/static/assets/132581110/7bdece9e-a266-45e3-bb5d-07000a9a92fe)
