### ISSUE TITLE
访问所有文件返回头都是no-cache

### ISSUE THREAD

**Issue by acfpop** [staticfile/static#694]
https://cdn.staticfile.net/vue/3.3.4/vue.global.prod.min.js

Access-Control-Allow-Credentials:
true

Access-Control-Allow-Headers:
Authorization, Content-Type, If-Match, If-Modified-Since, If-None-Match, If-Unmodifed-Since, X-CSRF-TOKEN, X-Requested-With,token
Access-Control-Allow-Methods:
GET, POST, PATCH, PUT, DELETE, OPTIONS
Access-Control-Allow-Origin:
*
Cache-Control:
no-cache
Content-Encoding:
gzip
Content-Type:
text/javascript; charset=utf-8
Date:
Tue, 19 Mar 2024 16:17:56 GMT
Server:
nginx
X-Cloud-Cdn:
true
X-Ser:
BC19_dx-sichuan-chengdu-29-cache-1, BC71_dx-jiangsu-taizhou-12-cache-1

**Comment by qinhongqi1234** [comment]
前一阵子才使用的no-cache，然后服务经常崩，刚才又崩了，所有静态文件都访问不到，临时换cdn，换完发现他又加了cache，服了

**Comment by zonefile** [comment]
@qinhongqi1234 尝试下南科大维护的 https://mirrors.sustech.edu.cn/cdnjs/ajax/libs/vue/3.3.4/vue.global.prod.min.js

将 cdn.staticfile.net 或 cdn.staticfile.org 替换为 mirrors.sustech.edu.cn/cdnjs/ajax/libs 即可
