### ISSUE TITLE
cdn.staticfile.net偶尔无法使用

### ISSUE THREAD

**Issue by fecent** [staticfile/static#696]
nslookup提示
*** 没有 cdn.staticfile.net 可以使用的 internal type for both IPv4 and IPv6 Addresses (A+AAAA)记录

使用org域名则正常，主站使用www.staticfile.net也正常，就是偶尔找不到这个cdn

**Comment by DengMingHao** [comment]
2024年4月28日，也是无法正常访问https://cdn.staticfile.net/vue/3.3.4/vue.cjs.js

**Comment by DMaxProfile** [comment]
目前是正常的
