### ISSUE TITLE
net域名的组件文件打不开

### ISSUE THREAD

**Issue by cschenzz** [staticfile/static#702]
org域名的可以打开
https://[cdn.staticfile.net](https://cdn.staticfile.net/docsify/4.13.1/docsify.min.js)/docsify/4.13.1/docsify.min.js

我用到了docsify, prism语法高亮, 搜索, 放大, 拷贝代码插件

**Comment by Tyrone2333** [comment]
好像所有cdn.staticfile.net都不行了

**Comment by cschenzz** [comment]
官网同个域名https://www.staticfile.net/是可以打开, 应该是cdn的二级域名出问题了

**Comment by DMaxProfile** [comment]
https://cdn.staticfile.net/docsify/4.13.1/docsify.min.js
目前正常
