### ISSUE TITLE
好多库的版本都没更新比如font-awesome

### ISSUE THREAD

**Issue by Xjystudio** [staticfile/static#704]
![image](https://github.com/user-attachments/assets/b7328db6-a47e-475a-9157-c3c48e8f905c)
![image](https://github.com/user-attachments/assets/fc2ae3b4-7544-44a6-93a6-f35c7715f5d5)

**Comment by DMaxProfile** [comment]
https://cdn.staticfile.net/font-awesome/6.7.0/js/all.min.js
在url更换版本号就可以用了， 官网那个稍后会更新
