### ISSUE TITLE
org网站域名切换为net为http协议

### ISSUE THREAD

**Issue by getwebtools** [staticfile/static#705]
https://cdn.staticfile.org/ 重定向到net后会将https协议变成http协议，导致网站无法加载js，大面积出错

**Comment by m68824454** [comment]
什么时候能好啊

**Comment by wanvb** [comment]
xxx.com.com/:1 Mixed Content: The page at 'https://xxx.com/' was loaded over HTTPS, but requested an insecure script 'http://cdn.staticfile.net/jquery/2.2.2/jquery.min.js'. This request has been blocked; the content must be served over HTTPS.
xxx.com.com/:1 Mixed Content: The page at 'https://xxx.com.com/' was loaded over HTTPS, but requested an insecure script 'http://cdn.staticfile.net/js-cookie/latest/js.cookie.min.js'. This request has been blocked; the content must be served over HTTPS.
哈哈我也遇到了，我还说网站怎么忽然就故障了，一大早客户就催飞了，及时换到bootcdn.cn一切正常了

**Comment by mpenglong** [comment]
受害者+1

**Comment by ww1024** [comment]
+1

**Comment by Francklin** [comment]
推荐使用web缓存网www.webcache.cn 替代

**Comment by DMaxProfile** [comment]
已处理
