### ISSUE TITLE
报跨域问题：has been blocked by CORS policy

### ISSUE THREAD

**Issue by uCloudCastle** [staticfile/static#706]
Access to fetch at 'https://cdn.staticfile.org/dayjs/1.11.9/dayjs.min.js' from origin '' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by Francklin** [comment]
要修改域名为 cdn.staticfile.net
