### ISSUE TITLE
麻烦同步一下tesseract.js-core

### ISSUE THREAD

**Issue by wz71014q** [staticfile/static#708]
麻烦同步一下tesseract.js-core，tesseract.js运行要依赖这个。其他的esseract.js-core CDN都太慢了。十分感谢！
[[tesseract.js-core](https://unpkg.com/browse/tesseract.js-core@1.0.2/)](https://unpkg.com/browse/tesseract.js-core@5.1.1/)

**Comment by Francklin** [comment]
staticfile已停止维护。推荐使用webcache缓存网 https://npm.webcache.cn/tesseract.js-core@5.1.1/

**Comment by DMaxProfile** [comment]
https://cdn.staticfile.net/tesseract.js/5.1.1/tesseract.min.js
