### ISSUE TITLE
可否支持下Lit

### ISSUE THREAD

**Issue by wencan** [staticfile/static#712]
Lit
https://github.com/lit/lit/

files: https://cdn.jsdelivr.net/gh/lit/dist/
doc: https://lit.dev/docs/getting-started/#use-bundles

**Comment by Francklin** [comment]
可以试试 https://npm.webcache.cn/lit-dist/

**Comment by DMaxProfile** [comment]
https://cdn.staticfile.net/lit/3.2.1/all/lit-all.min.js
https://cdn.staticfile.net/lit/3.2.1/all/lit-all.min.js.map
https://cdn.staticfile.net/lit/3.2.1/core/lit-core.min.js
https://cdn.staticfile.net/lit/3.2.1/core/lit-core.min.js.map
